### PR TITLE
Set the bucket resolution (optional) as part of the stream write command

### PR DESCRIPTION
**Pull request by davecromberge**
Part of https://github.com/dalmatinerdb/dalmatinerdb/issues/64

Could not get the quickcheck tests running locally because the fault/2 function is not supported on my (free) version of quickcheck.

### CODE REVIEW

**Comment by Licenser** [comment]
Can you add this to the protocol tests too?

**Comment by davecromberge** [comment]
@Licenser, sorry - could you be more specific about the tests you want me to update?  I will update the protocol documentation too.

**Comment by Licenser** [comment]
sorry I missed them :)

**Comment by Licenser** [comment]
thanks!

**Pull request merged**
